// Skeleton Code for a discord bot created by Jordan Phillips
// Created for creating a discord bot course on skillshare
// Created in 2020

var Discord = require('discord.io');


// YOURTOKENHERE Being whatever the autogenerated bot token from discord
// Connects your bot to discord
var bot = new Discord.Client({
   token: 'YOURTOKENHERE',
   autorun: true
});

// Will run when the bot becomes ready
bot.on('ready', function (evt) {
  // Outputs to your console when ready
  console.log('Successfully Connected');
});

// Will run whenever a user sends a message in the server
bot.on('message', function (user, userID, channelID, message, evt) {
  // Outputs the message into your console.
  // Try it Out!
  console.log(message);
});
